export const SET_INITIAL_LOCATION = 'SET_INITIAL_LOCATION';

export const SET_DESTINATION_PATH_STARTED = 'SET_DESTINATION_PATH_STARTED';
export const SET_DESTINATION_PATH_COMPLETED = 'SET_DESTINATION_PATH_COMPLETED';
export const SET_DESTINATION_PATH_FAILED = 'SET_DESTINATION_PATH_FAILED';

export const CURRENT_NODE_DELETED = 'CURRENT_NODE_DELETED';