matrix:
  include:
    - language: node_js
      node_js:
        - "9"
      script: .travis/ci_node.sh

    - language: node_js
      node_js:
        - "8"
      script: .travis/ci_node.sh
      
    - stage: Deploy Android 🤖
    if: branch = master AND type = push
    language: android
    jdk: oraclejdk8
    android:
      components:
        - tools
        - platform-tools
        - android-26
        - extra-google-m2repository
        - extra-google-google_play_services
    before_install:
      - nvm install 8.5.0
      - gem install bundler
      - bundle install
    before_script:
      - ./internals/scripts/travis/gitconfig.sh
    install: yarn
    script: npm run deployment:android