
export const LOGBOOK_FETCHING_STARTED = 'LOGBOOK_FETCHING_STARTED'
export const LOGBOOK_FETCHING_COMPLETED = 'LOGBOOK_FETCHING_COMPLETED'
export const LOGBOOK_FETCHING_FAILED = 'LOGBOOK_FETCHING_FAILED'
